### ISSUE TITLE
ERROR after filling captcha 

### ISSUE THREAD

**Issue by sudhanshu947** [suryavaddiraju/irctc-api#48]
Getting this error after filling captcha in terminal

Uncaught ReferenceError ReferenceError: RQHNm is not defined
    at <anonymous> (repl:1:1)

**Comment by suryavaddiraju** [comment]
you can try irctc-api@2.0.13 to give your custom `viu` binary full path in params object with `viu` as key in params and the value is viu package full binary path.
Please refer optional keys in [API Documentation](https://dev.vaddiraju.in/irctc-api/api_reference)

**Comment by suryavaddiraju** [comment]
Let me know whether the issue still persists

**Comment by sudhanshu947** [comment]
> Let me know whether the issue still persists

Still same issue after entering captcha...

**Comment by suryavaddiraju** [comment]
As it is an internal issue with your system, This issue stands closed, you want to reopen and you are free to do it.
