### ISSUE TITLE
Problem While Booking Tickets

### ISSUE THREAD

**Issue by btcparel** [suryavaddiraju/irctc-api#52]
1. Stuck After Tatkal Opening Time:

- When I log in before the Tatkal booking opens, the system waits as expected. However, even after the Tatkal booking time begins, the process continues to wait and does not proceed further.

2. Website Unreachable Error:

- The script frequently displays a "Website unreachable" error and then stops functioning. I have attempted to book tickets five times in both AC and SL Tatkal categories, but the same issue occurs each time.

**Comment by suryavaddiraju** [comment]
I would look deeper into your issue "Website unreachable error". if you can provide me logs displayed in your Console.


You can also describe what exactly needs to do to simulate the error.

**Comment by suryavaddiraju** [comment]
New version released, Ticket closed, Try with new version
