### ISSUE TITLE
Request for feature : Ticket Probability Status

### ISSUE THREAD

**Issue by ForceGT** [suryavaddiraju/irctc-api#53]
Hey, first of all, awesome stuff. Thanks for spending, countless hours dealing with reversing the shitty website

Just wanted to request the ability to check the Ticket Probabilty, which is available before booking any ticket

**Comment by suryavaddiraju** [comment]
Will do but it requires login process means entering answer to the captcha

**Comment by suryavaddiraju** [comment]
Currently working on organising IRCTC class and book ticket function. Will add your feature in next version

**Comment by ForceGT** [comment]
I think ConfirmTkt also scrapes from IRCTC, and gives the details right after checking PNR. Would appreciate if something like that can be done

**Comment by suryavaddiraju** [comment]
I think scrap and calls irctc server from their server using their IRCTC Credentials, If I implement the same I need to have a running server to mask my IRCTC Credentials.

If you help we can scrap ConfirmTKT API and add it to our module.

**Comment by ForceGT** [comment]
I'll see if I can scrap ConfirmTKT stuff

**Comment by suryavaddiraju** [comment]
Send me the link where we can check probability status in confirmTKT
