### ISSUE TITLE
What is the average time taken to book with test/ code during tatkal timings ?

### ISSUE THREAD

**Issue by ajithvcoder** [suryavaddiraju/irctc-api#63]
What is the average time taken to book with test/ code ? I am going to try booking tomorrow
this one https://github.com/suryavaddiraju/irctc-api/blob/main/test/book.mjs

**Comment by suryavaddiraju** [comment]
I haven't tried a tatkal ticket with the current version. You kindly update me the metrics once you try.

**Comment by ajithvcoder** [comment]
**Normal Train booking**

IST: 9:20 am
I booked from Virudhunagar to Kovilpatti (2S class, 1 pasanger) and pay is 40 ruppees
U need to enter two captchas and Approve payment(used gpay)
After first captcha there is a sleep time fo 20 seconds for single passenger entry but i think its customizable in code
Total Execution Time: 52.115s

But i think for each passenger input there is a sleep time so it may vary depending on passengers
Note: I think according to irctc we can't book more than 6 pasangers in a single attempt (I didnt test with this API)

**Takal booking Observations**

1. The timout time should be customizable i think because it takes a long time to even get the first captcha during 11.00 AM - 11:05 AM non-ac takal booking time
2. Even after entering captcha getting timeout error because of each api call.
3. I also think there can be a internal rule written in irctc that one user can login only once from 11 am to 11.10 am (not sure of it)


```
Error1:

node:internal/modules/run_main:122
    triggerUncaughtException(
    ^

ConnectTimeoutError: Connect Timeout Error (attempted addresses: 103.252.142.19:443, timeout: 10000ms)
    at onConnectTimeout (D:\train_ticket\node_modules\undici\lib\core\connect.js:232:24)
    at Immediate._onImmediate (D:\train_ticket\node_modules\undici\lib\core\connect.js:188:35)
    at process.processImmediate (node:internal/timers:491:21) {
  code: 'UND_ERR_CONNECT_TIMEOUT'
}
```

```
Error2: After captcha entering

Please type the above text and press enter
m@N3
node:internal/modules/run_main:122
    triggerUncaughtException(
    ^

Error: read ECONNRESET
    at TLSWrap.onStreamRead (node:internal/stream_base_commons:216:20) {
  errno: -4077,
  code: 'ECONNRESET',
  syscall: 'read'
}

Node.js v22.11.0
```

**Comment by ajithvcoder** [comment]
But its a great work . if you can fix the takal booking issue you can add a user interface and sell with your api keys for yearly or monthly subscription. Agents ask atleast 200 per takal booking.

**Comment by hdig** [comment]
i was trying to book Tatkal ticket today that is 09-11-2024 at 11.00 hrs through powershell and this is the error i faced many times: 
PS C:\Users\polu\node_modules\irctc-api> node booknow2.mjs
node:internal/modules/run_main:122
    triggerUncaughtException(
    ^

Error: read ECONNRESET
    at TLSWrap.onStreamRead (node:internal/stream_base_commons:216:20) {
  errno: -4077,
  code: 'ECONNRESET',
  syscall: 'read'
}

Node.js v22.11.0

**Comment by suryavaddiraju** [comment]
Try logging in before 3 Minutes i.e. if ticket is at 11:00 AM try starting run at 10:57 AM, If ticket is at 10:00 AM Try starting run at 09:57 AM.

**Comment by ajithvcoder** [comment]
but takal quota opens at 11:00 am sharp

**Comment by hdig** [comment]
how to login ? If I just simply run the command at 09.57 / 10.57 : node booknow.mjs , then the script will just attempt to login and book before the tatkal timing , correct me please if i am wrong here

**Comment by suryavaddiraju** [comment]
It is designed to login at 09:58 AM and checks for ticket at 10:00 AM where your class is AC and quota is Tatkal for Non AC the same behaviour but at 10:58 and 11:00 AM

**Comment by hdig** [comment]
Thanks for the clarification , I will test it and let you know the results.

**Comment by suryavaddiraju** [comment]
Any updates?

**Comment by hdig** [comment]
Sir, I will try Tatkal ticket tomorrow for ac and sleeper both . And i Will let you know the results.

**Comment by ajithvcoder** [comment]
@hdig kindly use a timer to count the end time of this line https://github.com/ajithvcoder/irctc-api/blob/main/examples/book.mjs#L33 so that we will know how much time it takes

**Comment by hdig** [comment]
![Screenshot 2024-11-14 101555](https://github.com/user-attachments/assets/932af032-a851-4416-868a-35653b1a801c)
I tried 3RD AC TATKAL and here is what happened.

**Comment by ajithvcoder** [comment]
Hi, I think  paytm and redbus are also using these type of apis. They are blocked during 11.00 am to 11.10 am and 10.00 am to 10.10 am so the api used in this repo could also be blocked during those times

**Comment by kukrejas9268** [comment]
This code is only for normal bookings, these api gets blocked by IRCTC during tatkal timings weather you implement any statergy, nothing is gonna work. IRCTC has a specific api for tatkal timings and no body can have it.

**Comment by ajithvcoder** [comment]
Ya even Paytm and redbus too use similar APIs I think they are blocked from 11.00 am to 11.10 am

**Comment by rockydares** [comment]
I am trying this script for 3 days (Tatkal SL booking at 11AM) and I have received the UPI payment request for once till now, but after payment it could not book though.

**Comment by fuhcq3** [comment]
So did it work for you @rockydares ? Have you tried using the IRCTC wallet instead? Does the tatkal booking work for anyone?
